name: Update Minecraft Versions

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Полная история коммитов нужна для git diff

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run script to generate versions.md
        run: python generate_minecraft_versions.py

      - name: Commit and push if file changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Проверяем, изменился ли файл
          git diff --quiet temp/versions.md || {
            git add temp/versions.md
            git commit -m "Update Minecraft versions [skip ci]"
            git push
          }
