name: Update Minecraft Versions

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run script to generate versions.md
        run: python generate_minecraft_versions.py

      - name: Check versions.md hash and move file
        run: |
          if [ -f versions.md ]; then
            old_hash=$(sha256sum versions.md | cut -d ' ' -f 1)
            new_hash=$(sha256sum temp/versions.md | cut -d ' ' -f 1)
            if [ "$old_hash" != "$new_hash" ]; then
              mv temp/versions.md versions.md
            else
              echo "No changes in versions.md"
              rm temp/versions.md
            fi
          else
            mv temp/versions.md versions.md
          fi

      - name: Commit and push updated versions.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add versions.md
          git commit -m "Update versions.md with latest Minecraft versions" || echo "Нет изменений для коммита"
          git push origin main
